-- Miracle55 Worldcup Clean Final SQL
-- รันไฟล์นี้ 1 ครั้งใน Supabase SQL Editor
-- รวมแก้ schema, match_key, duplicate predictions, unique index, RLS และ reload schema

-- 1) สร้างตารางหลักถ้ายังไม่มี
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  full_name text,
  total_points integer default 0,
  created_at timestamptz default now()
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  match_key text,
  team_a text,
  team_b text,
  match_time timestamptz,
  score_a integer,
  score_b integer,
  actual_score_a integer,
  actual_score_b integer,
  actual_winner text,
  is_finished boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  match_id bigint,
  match_key text,
  stage text,
  team_a text,
  team_b text,
  pred_a integer,
  pred_b integer,
  predicted_winner text,
  top_scorer_guess text,
  points_awarded integer default 0,
  scored_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 2) เติมคอลัมน์ที่โค้ดใช้งาน เผื่อมีตารางเก่าอยู่แล้ว
alter table public.users add column if not exists username text;
alter table public.users add column if not exists full_name text;
alter table public.users add column if not exists total_points integer default 0;
alter table public.users add column if not exists created_at timestamptz default now();

alter table public.matches add column if not exists match_key text;
alter table public.matches add column if not exists team_a text;
alter table public.matches add column if not exists team_b text;
alter table public.matches add column if not exists match_time timestamptz;
alter table public.matches add column if not exists score_a integer;
alter table public.matches add column if not exists score_b integer;
alter table public.matches add column if not exists actual_score_a integer;
alter table public.matches add column if not exists actual_score_b integer;
alter table public.matches add column if not exists actual_winner text;
alter table public.matches add column if not exists is_finished boolean default false;
alter table public.matches add column if not exists created_at timestamptz default now();
alter table public.matches add column if not exists updated_at timestamptz default now();

alter table public.predictions add column if not exists user_id bigint;
alter table public.predictions add column if not exists match_id bigint;
alter table public.predictions add column if not exists match_key text;
alter table public.predictions add column if not exists stage text;
alter table public.predictions add column if not exists team_a text;
alter table public.predictions add column if not exists team_b text;
alter table public.predictions add column if not exists pred_a integer;
alter table public.predictions add column if not exists pred_b integer;
alter table public.predictions add column if not exists predicted_winner text;
alter table public.predictions add column if not exists top_scorer_guess text;
alter table public.predictions add column if not exists points_awarded integer default 0;
alter table public.predictions add column if not exists scored_at timestamptz;
alter table public.predictions add column if not exists created_at timestamptz default now();
alter table public.predictions add column if not exists updated_at timestamptz default now();

-- 3) เติม match_key ให้ matches เดิม
update public.matches
set match_key = 'm-' || id::text
where match_key is null and id between 1 and 16;

-- 4) seed คู่บอลรอบแรก ถ้ายังไม่มี
insert into public.matches (id, match_key, team_a, team_b, is_finished)
select v.id, v.match_key, v.team_a, v.team_b, false
from (values
  (1, 'm-1', 'บราซิล', 'อังกฤษ'),
  (2, 'm-2', 'ฝรั่งเศส', 'อาร์เจนตินา'),
  (3, 'm-3', 'สเปน', 'เยอรมนี'),
  (4, 'm-4', 'โปรตุเกส', 'อิตาลี'),
  (5, 'm-5', 'เนเธอร์แลนด์', 'โครเอเชีย'),
  (6, 'm-6', 'เบลเยียม', 'โมร็อกโก'),
  (7, 'm-7', 'ญี่ปุ่น', 'เกาหลีใต้'),
  (8, 'm-8', 'อุรุกวัย', 'เซเนกัล'),
  (9, 'm-9', 'สหรัฐอเมริกา', 'เม็กซิโก'),
  (10, 'm-10', 'สวิตเซอร์แลนด์', 'เดนมาร์ก'),
  (11, 'm-11', 'ออสเตรเลีย', 'ซาอุดีอาระเบีย'),
  (12, 'm-12', 'แคนาดา', 'เอกวาดอร์'),
  (13, 'm-13', 'ตูนิเซีย', 'โปแลนด์'),
  (14, 'm-14', 'ยูเครน', 'เวลส์'),
  (15, 'm-15', 'สวีเดน', 'ออสเตรีย'),
  (16, 'm-16', 'กานา', 'แคเมอรูน')
) as v(id, match_key, team_a, team_b)
where not exists (select 1 from public.matches m where m.match_key = v.match_key);

-- 5) sync predictions.match_key จาก match_id ให้ข้อมูลเก่า
update public.predictions p
set match_key = m.match_key
from public.matches m
where p.match_key is null
  and p.match_id = m.id;

-- 6) ลบข้อมูล predictions เก่าที่ไม่มี match_key เพราะเป็นข้อมูล test/เสีย ใช้ upsert ไม่ได้
-- ถ้าต้องการเก็บข้อมูลเก่าทั้งหมด ให้สำรองก่อนรันไฟล์นี้
delete from public.predictions
where match_key is null;

-- 7) ล้าง unique เดิมก่อนจัดการ duplicate
alter table public.predictions drop constraint if exists predictions_user_match_key_unique;
drop index if exists public.predictions_user_match_key_unique;

-- 8) ลบ duplicate user_id + match_key โดยเก็บรายการล่าสุดไว้
with ranked as (
  select
    id,
    row_number() over (
      partition by user_id, match_key
      order by updated_at desc nulls last, created_at desc nulls last, id desc
    ) as rn
  from public.predictions
  where user_id is not null
    and match_key is not null
)
delete from public.predictions p
using ranked r
where p.id = r.id
  and r.rn > 1;

-- 9) สร้าง unique index ใหม่ ป้องกันกดส่งซ้ำ
create unique index predictions_user_match_key_unique
on public.predictions(user_id, match_key);

-- 10) unique index อื่น ๆ
create unique index if not exists matches_match_key_unique
on public.matches(match_key);

create unique index if not exists users_username_unique
on public.users(username);

-- 11) เติม actual_winner ให้รายการเก่าที่มี score แล้วแต่ยังไม่มี winner
update public.matches
set actual_winner = case
  when actual_score_a > actual_score_b then team_a
  when actual_score_b > actual_score_a then team_b
  else actual_winner
end
where actual_score_a is not null
  and actual_score_b is not null
  and actual_winner is null;

-- 12) เปิด RLS และ policy แบบ static web สำหรับทดสอบ/ใช้งานเบื้องต้น
alter table public.users enable row level security;
alter table public.matches enable row level security;
alter table public.predictions enable row level security;

drop policy if exists miracle55_users_anon_all on public.users;
drop policy if exists miracle55_matches_anon_all on public.matches;
drop policy if exists miracle55_predictions_anon_all on public.predictions;

create policy miracle55_users_anon_all on public.users
for all to anon using (true) with check (true);

create policy miracle55_matches_anon_all on public.matches
for all to anon using (true) with check (true);

create policy miracle55_predictions_anon_all on public.predictions
for all to anon using (true) with check (true);

-- 13) grant สิทธิ์ให้ anon/authenticated
 grant usage on schema public to anon, authenticated;
 grant select, insert, update, delete on public.users to anon, authenticated;
 grant select, insert, update, delete on public.matches to anon, authenticated;
 grant select, insert, update, delete on public.predictions to anon, authenticated;
 grant usage, select on all sequences in schema public to anon, authenticated;

-- 14) reload schema cache
notify pgrst, 'reload schema';

-- 15) ตรวจผลหลังรัน: ถ้า query แรกไม่คืนแถว = ไม่มี duplicate แล้ว
select user_id, match_key, count(*) as rows_count
from public.predictions
group by user_id, match_key
having count(*) > 1;

select id, match_key, team_a, team_b, actual_score_a, actual_score_b, actual_winner, is_finished
from public.matches
order by id
limit 80;
