-- Miracle55 Worldcup CLEAN FINAL SQL
-- รันไฟล์นี้ 1 ครั้งใน Supabase SQL Editor
-- จุดประสงค์: ปรับตารางเก่าให้เข้ากับโค้ดชุดใหม่ โดยไม่ลบข้อมูลเดิม

-- 1) USERS
create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  username text unique not null,
  full_name text,
  total_points integer default 0,
  created_at timestamptz default now()
);

alter table public.users add column if not exists username text;
alter table public.users add column if not exists full_name text;
alter table public.users add column if not exists total_points integer default 0;
alter table public.users add column if not exists created_at timestamptz default now();

create unique index if not exists users_username_unique on public.users(username);

-- 2) MATCHES: รองรับทั้ง schema เก่า id/team_a/team_b และ schema ใหม่ match_key
create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  team_a text,
  team_b text,
  match_key text,
  actual_score_a integer,
  actual_score_b integer,
  actual_winner text,
  is_finished boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.matches add column if not exists match_key text;
alter table public.matches add column if not exists team_a text;
alter table public.matches add column if not exists team_b text;
alter table public.matches add column if not exists actual_score_a integer;
alter table public.matches add column if not exists actual_score_b integer;
alter table public.matches add column if not exists actual_winner text;
alter table public.matches add column if not exists is_finished boolean default false;
alter table public.matches add column if not exists created_at timestamptz default now();
alter table public.matches add column if not exists updated_at timestamptz default now();

-- เติม match_key ให้แถวเดิม m-1, m-2, ... ตาม id
update public.matches
set match_key = 'm-' || id::text
where match_key is null and id is not null;

-- เติม actual_winner จากผลจริง ถ้ายังว่าง
update public.matches
set actual_winner = case
  when actual_score_a > actual_score_b then team_a
  when actual_score_b > actual_score_a then team_b
  else actual_winner
end
where actual_winner is null
  and actual_score_a is not null
  and actual_score_b is not null;

create unique index if not exists matches_match_key_unique on public.matches(match_key);

-- 3) PREDICTIONS
create table if not exists public.predictions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete cascade,
  match_id integer,
  match_key text not null,
  stage text,
  team_a text,
  team_b text,
  pred_a integer,
  pred_b integer,
  predicted_winner text,
  top_scorer_guess text,
  points_awarded integer default 0,
  scored_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.predictions add column if not exists user_id uuid references public.users(id) on delete cascade;
alter table public.predictions add column if not exists match_id integer;
alter table public.predictions add column if not exists match_key text;
alter table public.predictions add column if not exists stage text;
alter table public.predictions add column if not exists team_a text;
alter table public.predictions add column if not exists team_b text;
alter table public.predictions add column if not exists pred_a integer;
alter table public.predictions add column if not exists pred_b integer;
alter table public.predictions add column if not exists predicted_winner text;
alter table public.predictions add column if not exists top_scorer_guess text;
alter table public.predictions add column if not exists points_awarded integer default 0;
alter table public.predictions add column if not exists scored_at timestamptz;
alter table public.predictions add column if not exists created_at timestamptz default now();
alter table public.predictions add column if not exists updated_at timestamptz default now();

-- ถ้า prediction เก่าใช้ match_id แต่ยังไม่มี match_key ให้แปลงเป็น m-id
update public.predictions
set match_key = 'm-' || match_id::text
where match_key is null and match_id is not null;

create unique index if not exists predictions_user_match_key_unique on public.predictions(user_id, match_key);

-- 4) RLS + Policies สำหรับเว็บ static + anon key
alter table public.users enable row level security;
alter table public.matches enable row level security;
alter table public.predictions enable row level security;

drop policy if exists miracle55_users_anon_all on public.users;
drop policy if exists miracle55_matches_anon_all on public.matches;
drop policy if exists miracle55_predictions_anon_all on public.predictions;

create policy miracle55_users_anon_all
on public.users
for all
to anon
using (true)
with check (true);

create policy miracle55_matches_anon_all
on public.matches
for all
to anon
using (true)
with check (true);

create policy miracle55_predictions_anon_all
on public.predictions
for all
to anon
using (true)
with check (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.users to anon, authenticated;
grant select, insert, update, delete on public.matches to anon, authenticated;
grant select, insert, update, delete on public.predictions to anon, authenticated;

grant usage, select on all sequences in schema public to anon, authenticated;

-- 5) Reload schema cache ของ Supabase/PostgREST
notify pgrst, 'reload schema';

-- 6) ตรวจสอบผลลัพธ์
select id, match_key, team_a, team_b, actual_score_a, actual_score_b, actual_winner, is_finished
from public.matches
order by id
limit 80;
