-- 00_RUN_THIS_SQL_FIRST.sql
-- Miracle55 Worldcup clean setup + Top20 Leaderboard support
-- รันไฟล์นี้ใน Supabase SQL Editor ได้ซ้ำอย่างปลอดภัย

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  full_name text,
  total_points integer default 0,
  created_at timestamptz default now()
);

create table if not exists public.matches (
  id integer primary key,
  match_key text unique,
  team_a text,
  team_b text,
  match_time timestamptz,
  score_a integer,
  score_b integer,
  actual_score_a integer,
  actual_score_b integer,
  actual_winner text,
  is_finished boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  match_id integer,
  match_key text,
  stage text,
  team_a text,
  team_b text,
  pred_a integer,
  pred_b integer,
  predicted_winner text,
  top_scorer_guess text,
  points_awarded integer default 0,
  scored_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.matches add column if not exists match_key text;
alter table public.matches add column if not exists team_a text;
alter table public.matches add column if not exists team_b text;
alter table public.matches add column if not exists actual_score_a integer;
alter table public.matches add column if not exists actual_score_b integer;
alter table public.matches add column if not exists actual_winner text;
alter table public.matches add column if not exists is_finished boolean default false;
alter table public.predictions add column if not exists match_key text;
alter table public.predictions add column if not exists stage text;
alter table public.predictions add column if not exists team_a text;
alter table public.predictions add column if not exists team_b text;
alter table public.predictions add column if not exists pred_a integer;
alter table public.predictions add column if not exists pred_b integer;
alter table public.predictions add column if not exists predicted_winner text;
alter table public.predictions add column if not exists top_scorer_guess text;
alter table public.predictions add column if not exists points_awarded integer default 0;
alter table public.predictions add column if not exists scored_at timestamptz;
alter table public.predictions add column if not exists updated_at timestamptz default now();

update public.matches set match_key = 'm-' || id::text where match_key is null and id between 1 and 16;
update public.predictions p set match_key = 'm-' || p.match_id::text where p.match_key is null and p.match_id is not null;

insert into public.matches (id, match_key, team_a, team_b, is_finished)
values
(1,'m-1','บราซิล','อังกฤษ',false),
(2,'m-2','ฝรั่งเศส','อาร์เจนตินา',false),
(3,'m-3','สเปน','เยอรมนี',false),
(4,'m-4','โปรตุเกส','อิตาลี',false),
(5,'m-5','เนเธอร์แลนด์','โครเอเชีย',false),
(6,'m-6','เบลเยียม','โมร็อกโก',false),
(7,'m-7','ญี่ปุ่น','เกาหลีใต้',false),
(8,'m-8','อุรุกวัย','เซเนกัล',false),
(9,'m-9','สหรัฐอเมริกา','เม็กซิโก',false),
(10,'m-10','สวิตเซอร์แลนด์','เดนมาร์ก',false),
(11,'m-11','ออสเตรเลีย','ซาอุดีอาระเบีย',false),
(12,'m-12','แคนาดา','เอกวาดอร์',false),
(13,'m-13','ตูนิเซีย','โปแลนด์',false),
(14,'m-14','ยูเครน','เวลส์',false),
(15,'m-15','สวีเดน','ออสเตรีย',false),
(16,'m-16','กานา','แคเมอรูน',false)
on conflict (id) do update
set match_key = excluded.match_key,
    team_a = coalesce(public.matches.team_a, excluded.team_a),
    team_b = coalesce(public.matches.team_b, excluded.team_b);

drop index if exists predictions_user_match_key_unique;

with ranked as (
  select
    id,
    row_number() over (
      partition by user_id, match_key
      order by updated_at desc nulls last, created_at desc nulls last, id desc
    ) as rn
  from public.predictions
  where user_id is not null
    and match_key is not null
)
delete from public.predictions p
using ranked r
where p.id = r.id
  and r.rn > 1;

create unique index if not exists predictions_user_match_key_unique
on public.predictions(user_id, match_key)
where match_key is not null;

alter table public.users enable row level security;
alter table public.matches enable row level security;
alter table public.predictions enable row level security;

drop policy if exists miracle55_users_anon_all on public.users;
drop policy if exists miracle55_matches_anon_all on public.matches;
drop policy if exists miracle55_predictions_anon_all on public.predictions;

create policy miracle55_users_anon_all on public.users for all to anon using (true) with check (true);
create policy miracle55_matches_anon_all on public.matches for all to anon using (true) with check (true);
create policy miracle55_predictions_anon_all on public.predictions for all to anon using (true) with check (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.users to anon, authenticated;
grant select, insert, update, delete on public.matches to anon, authenticated;
grant select, insert, update, delete on public.predictions to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

notify pgrst, 'reload schema';

select user_id, match_key, count(*) as rows_count
from public.predictions
group by user_id, match_key
having count(*) > 1;

select id, match_key, team_a, team_b, actual_score_a, actual_score_b, actual_winner, is_finished
from public.matches
order by id
limit 80;
